### ISSUE TITLE
vim_mode: true is not working in emacs

### ISSUE THREAD

**Issue by linchen2chris** [einverne/einverne.github.io#35]
I add 
```
patch:
  app_options:
    com.jetbrains.intellij:
      ascii_mode: true
      vim_mode: true
    org.gnu.Emacs:
      ascii_mode: true
      vim_mode: true
``` 
in squirrel.custom.yaml, vim_mode works for intellij, but not works for my emacs.
